#server:
#  port: 8081;

spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: greyHound@2001
  dbcp2:
    validation-query: SELECT 1

spring:
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect



